### ISSUE TITLE
Test sets include Java plugin test source set by default

### ISSUE THREAD

**Issue by pkoenig10** [unbroken-dome/gradle-testsets-plugin#101]
I'm not sure if this intentional, but this can cause unexpected behavior because these tests sets are used to configure other plugins. For example, because of this the test source sets (`testCompileClasspath`, `testRuntimeClasspath`, and `testAnnotationProcessor`) are [duplicated](https://github.com/unbroken-dome/gradle-testsets-plugin/blob/126bd9987c9ab1b301de6342549237cffec11164/src/main/kotlin/org/unbrokendome/gradle/plugins/testsets/internal/IdeaModuleObserver.kt#L62-L70) in the IDEA module scopes. These configurations are already added to the IDEA module scopes [by the IDEA plugin](https://github.com/gradle/gradle/blob/0f0341236e25fe01a403b3994390616e311d6d78/subprojects/ide/src/main/java/org/gradle/plugins/ide/idea/IdeaPlugin.java#L442-L445).

Here a minimal reproduction of the issue:

*build.gradle:*
```
plugins {
    id 'java'
    id 'idea'
    id 'org.unbroken-dome.test-sets' version '2.2.1'
}

task testSetsInfo {
    doLast {
        testSets.each {
            println it
        }
    }
}

task scopesInfo {
    doLast {
        idea.module.scopes.TEST.plus.each {
            println it
        }
    }
}
```

*Output:*
```
$ gradle testSetsInfo

> Task :testSetsInfo
org.unbrokendome.gradle.plugins.testsets.dsl.PredefinedUnitTestSet@2822f626

BUILD SUCCESSFUL in 798ms
1 actionable task: 1 executed
```
```
$ gradle scopesInfo

> Task :scopesInfo
configuration ':testCompileClasspath'
configuration ':testRuntimeClasspath'
configuration ':testAnnotationProcessor'
configuration ':testCompileClasspath'
configuration ':testRuntimeClasspath'
configuration ':testAnnotationProcessor'

BUILD SUCCESSFUL in 659ms
1 actionable task: 1 executed
```

**Comment by tkrullmann** [comment]
Thanks for pointing this out. I think the `IdeaModuleObserver` should not be installed on the predefined `unitTest` set.
