### ISSUE TITLE
Jacoco integration test report does not include groovy spock tests

### ISSUE THREAD

**Issue by adithshenoy** [unbroken-dome/gradle-testsets-plugin#111]
Folder structure:

- src
   - integrationTest
      - groovy
         - tests
     - java
       - tests

As seen in the image below, java tests come in the jacoco coverage. However, groovy spock testcases are being ignored.

![image](https://user-images.githubusercontent.com/6744743/82606205-5e37de80-9bbf-11ea-96cc-7b9d6c3b2521.png)

Code:

```
testSets {
    integrationTest
}

test {
    testLogging { events "passed", "skipped", "failed", "standardError" }
}

integrationTest {
    testLogging { events "passed", "skipped", "failed", "standardError" }
}

jacocoTestReport {
    reports {
        xml.enabled true
    }
}

jacocoIntegrationTestReport {
    reports {
        xml.enabled true
    }
}
```

**Comment by tkrullmann** [comment]
I tried to reproduce this with a simple Spock test and the coverage was reported fine. In any case, the plugin doesn't really integrate deeply with Jacoco, all it does is set up a `JacocoReport` task for each test set (which seems to work here, as the `jacocoIntegrationTestReport` task is available). So if there is any bug, it is likely with the Gradle Jacoco plugin or Spock.
