### ISSUE TITLE
Could not find method compileIntegrationTestKotlin() 

### ISSUE THREAD

**Issue by antonydenyer** [unbroken-dome/gradle-testsets-plugin#112]
I was trying to do the following in my `build.gradle`

```
compileIntegrationTestKotlin {
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8
    }
}
```
but am getting the error "Could not find method compileIntegrationTestKotlin()" 

I've worked round the issue with:

```
tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8
    }
}
```

But, conceivably you might want to have your tests use 1.8 and implementation 1.6

**Comment by tkrullmann** [comment]
Cannot reproduce this; most likely the first block referencing the `compileIntegrationTestKotlin` task was declared before the `testSets` in the Gradle script.
