### ISSUE TITLE
Reports, binary and xml test output all mixed up with 1.2.0

### ISSUE THREAD

**Issue by wujek-srujek** [unbroken-dome/gradle-testsets-plugin#12]
With the default settings of the testsets plugin for the stardard test set and custom integrationTest, the results (binary and junit xml), and the reports are all mixed up. For the project available here (master): https://github.com/wujek-srujek/testsets, here is what it looks like after invoking the build:

$ cd build/
$ find test-results -type f
test-results/binary/integrationTest/results.bin
test-results/binary/integrationTest/output.bin
test-results/binary/integrationTest/output.bin.idx
test-results/binary/test/results.bin
test-results/binary/test/output.bin
test-results/binary/test/output.bin.idx
test-results/TEST-com.test.UnitTestSpecification.xml

As you can see, the test-results contains the xml files for unit tests, but binary files for both test types.

$ find integrationTest-results -type f
integrationTest-results/TEST-com.integrationTest.IntegrationTestSpecification.xml

$ find integrationTest -type f
integrationTest/classes/com.integrationTest.IntegrationTestSpecification.html
integrationTest/js/report.js
integrationTest/css/style.css
integrationTest/css/base-style.css
integrationTest/packages/com.integrationTest.html
integrationTest/index.html

The reports for integrationTest are directly in the build folder.

$ find reports/tests -type f
reports/tests/classes/com.test.UnitTestSpecification.html
reports/tests/js/report.js
reports/tests/css/style.css
reports/tests/css/base-style.css
reports/tests/packages/com.test.html
reports/tests/index.html

Whereas the reports for the default tests are in the build/reports folder.

When using the following settings (see testsets-separate-folders branch):
tasks.withType(Test) {
    reports.html.destination = new File(project.reportsDir, name)
    reports.junitXml.destination = new File(project.buildDir, "${name}-results")
    binResultsDir = new File(reports.junitXml.destination, 'binary')
}

the results are now:

$ cd build/
$ find test-results -type f
test-results/binary/results.bin
test-results/binary/output.bin
test-results/binary/output.bin.idx
test-results/TEST-com.test.UnitTestSpecification.xml

$ find integrationTest-results -type f
integrationTest-results/TEST-com.integrationTest.IntegrationTestSpecification.xml
integrationTest-results/binary/results.bin
integrationTest-results/binary/output.bin
integrationTest-results/binary/output.bin.idx

So, the binary and xml results are nicely separated and exist in their dedicated folders.

$ find reports/test -type f
reports/test/classes/com.test.UnitTestSpecification.html
reports/test/js/report.js
reports/test/css/style.css
reports/test/css/base-style.css
reports/test/packages/com.test.html
reports/test/index.html

$ find reports/integrationTest -type f
reports/integrationTest/classes/com.integrationTest.IntegrationTestSpecification.html
reports/integrationTest/js/report.js
reports/integrationTest/css/style.css
reports/integrationTest/css/base-style.css
reports/integrationTest/packages/com.integrationTest.html
reports/integrationTest/index.html

Similarly, all reports are under build/reports, and in correct folders. This is also consistent with the default layout/structure for the default test task without the testsets plugin applied.

I guess it would be really nice if the plugin provided such nice separation and segregation by default, i.e. add similar configuration in TestTaskListener.groovy.

**Comment by wujek-srujek** [comment]
Gradle 3.0 now provides such separation by default, so whatever this plugin sets should be undone when 3.0 is used to be consistent with Gradle defaults.

**Comment by rkrisztian** [comment]
Indeed Gradle 3 organizes test results and reports much better (see `JavaBasePlugin`). I would like to see these conventions followed by the TestSets plugin:

```
        xmlReport.getConventionMapping().map("destination", new Callable<Object>() {
            public Object call() throws Exception {
                return new File(convention.getTestResultsDir(), test.getName());
            }
        });
        htmlReport.getConventionMapping().map("destination", new Callable<Object>() {
            public Object call() throws Exception {
                return new File(convention.getTestReportDir(), test.getName());
            }
        });
        test.getConventionMapping().map("binResultsDir", new Callable<Object>() {
            public Object call() throws Exception {
                return new File(convention.getTestResultsDir(), test.getName() + "/binary");
            }
        });
```

The current solution makes the `build` directory look rather messy.

**Comment by wujek-srujek** [comment]
If it is of any help, this is what I currently use to un-do the customizations introduced by this plugin:

    afterEvaluate {
        tasks.withType(Test) {
            // the testsets plugin changes test report and result directories but they are mixed up
            // and different than Gradle 3.x defaults (the plugin existed before that)
            // set the directories as Gradle itself would do it
            reports.html.destination = new File(project.testReportDir, name)
            reports.junitXml.destination = new File(project.testResultsDir, name)

**Comment by dbalakirev** [comment]
The workaround proposed by @wujek-srujek works fine.

However I am hoping to see my PR merged (see linked above).

**Comment by tkrullmann** [comment]
Marking this as fixed. Thanks @dbalakirev!
