### ISSUE TITLE
Java 7 compatibility

### ISSUE THREAD

**Issue by dbalakirev** [unbroken-dome/gradle-testsets-plugin#13]
The documentation states I can use the plugin with Java 7.

I saw this issue where this caused problems: 
https://github.com/unbroken-dome/gradle-testsets-plugin/issues/1

Is it possible that this problem is present again from versions > 1.0.2? I tried with 1.1.0 and 1.2.0 and got the same error. 

Thanks for your response (and for the plugin)!

**Comment by denisrosca** [comment]
+1
Can we get a version cross-compiled to jdk7?
~~I didn't see anything in the code that requires java 8. I'm assuming this is caused by a change on the machine that this library is built with (switched to jdk8).~~
I was wrong, it does use classes available only on java 8.

**Comment by Dispader** [comment]
:+1:

**Comment by CrispyShot** [comment]
:+1:

**Comment by uschi2000** [comment]
+1

**Comment by acisternino** [comment]
+1

**Comment by mbelling** [comment]
+1

**Comment by basil** [comment]
+1
