### ISSUE TITLE
Plugin application fails on Gradle 8.0

### ISSUE THREAD

**Issue by catostrophe** [unbroken-dome/gradle-testsets-plugin#131]
This fails since `AbstractArchiveTask#setClassifier` is dropped in Gradle 8.0.

https://github.com/unbroken-dome/gradle-testsets-plugin/blob/1c6fc3fa1d23af767c6c6fb276308adf89aaf2e9/src/main/kotlin/org/unbrokendome/gradle/plugins/testsets/TestSetsPlugin.kt#L133

**Comment by tomasbjerre** [comment]
I switched to [JVM Test Suite](https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html) (as suggested in https://github.com/unbroken-dome/gradle-testsets-plugin/pull/132) and ended up with:

```groovy

testing {
   suites {
      test {
         useJUnitJupiter()
      }
      integTest(JvmTestSuite) {
         sources.java.srcDirs = ['src/integtest/java']
         sources.resources.srcDirs = ['src/integtest/resources']
         dependencies {
            implementation project()
            implementation sourceSets.test.output
         }
         targets {
            all {
               testTask.configure {
                  shouldRunAfter(test)
               }
            }
         }
      }
   }
}

configurations {
   integTestImplementation.extendsFrom testImplementation
}

tasks.named('check') { 
   dependsOn(testing.suites.integTest)
}

tasks.named("sourcesJar") {
   dependsOn("compileJava")
   dependsOn("compileTestJava")
   dependsOn("compileIntegTestJava")
}
tasks.named("javadoc") {
   dependsOn("compileJava")
   dependsOn("compileTestJava")
   dependsOn("compileIntegTestJava")
}
```

**Comment by jimshowalter** [comment]
The fix is to replace classifier with archiveClassifier, at least according to https://discuss.gradle.org/t/publishing-jars-with-classifiers-after-v5-0/30144

**Comment by jimshowalter** [comment]
Here's the bug: https://github.com/unbroken-dome/gradle-testsets-plugin/blob/1c6fc3fa1d23af767c6c6fb276308adf89aaf2e9/src/main/kotlin/org/unbrokendome/gradle/plugins/testsets/TestSetsPlugin.kt#L130-L133

**Comment by jimshowalter** [comment]
So either gradle-testsets-plugin can't ever be used with Gradle 8.x or newer, or has to be non-backward-compatible with Gradle earlier than 5.1. It's not possible to have it both ways (unless the repo is forked).

**Comment by jimshowalter** [comment]
@tkrullmann @cpiotr

**Comment by rkrisztian** [comment]
@tomasbjerre thanks for your example code, the JVM Test Suite seems indeed a more future-proof solution for what we so far have set up using the test sets plugin. However, I'd avoid setting these:

```groovy
         // Breaks conventions :(
         sources.java.srcDirs = ['src/integtest/java']
         sources.resources.srcDirs = ['src/integtest/resources']
```

If you just remove those lines and let them get derived from convention, then you end up with the folder `src/integTest/`. It's not  bad IMO, using uppercase letters in paths. Several paths in Gradle are named after the task name, e.g., HTML reports. So you will also be consistent just by letting the conventions do their job, leading to easier-to-use builds.

**Comment by jimshowalter** [comment]
This bug can probably be fixed via reflection.

First use reflection try to get the task.archiveClassifier declared field.

If present, use reflection to set the field.

If not present, use reflection to get the task.classifier field, make it accessible, and set it.

**Comment by dhakehurst** [comment]
This bug is also a problem for me...I need to use gradle 8 (actually 8.1.1),
when will there be a new release compatible ?

**Comment by rkrisztian** [comment]
@dhakehurst, the JVM Test Suite feature can pretty much replace what this plugin does, see conversation above.

**Comment by rkrisztian** [comment]
It looks like Gradle's built-in solution can still hurt us if we want back the following behavior configured for all subprojects without code duplication:

> A dependency configuration named integrationTestImplementation, which extends from "testImplementation";

In detail, see https://github.com/gradle/gradle/issues/19870#issuecomment-1669546935 .
