### ISSUE TITLE
Not supporting customized src files locations

### ISSUE THREAD

**Issue by langyizhao** [unbroken-dome/gradle-testsets-plugin#14]
Our project has its regression tests in test/regression folder with resources in testdata folder.

However with this plugin, by using dirName='regression' it only sets to src/regression/java and src/regression/resources

No way to specify sources and resources outside of src folder. (Or is there a workaround?)

**Comment by tkrullmann** [comment]
The testSet regression creates a source set that can be modified like any other, for example

```groovy
testSets { regression }

sourceSets {
  regression {
    resources.srcDir file('/my/custom/dir')
  }
}
```
