### ISSUE TITLE
Have to compile whole project to run single integration test method in IntelliJ

### ISSUE THREAD

**Issue by mcandre** [unbroken-dome/gradle-testsets-plugin#15]
There's an odd disconnect between the Gradle TestSets plugin and IntelliJ: I can execute the whole integration test suite in IntelliJ easily, but I can't right-click and run/debug an individual integration test method, unless I manually recompile the whole project in IntelliJ.

**Comment by JasonKDarby** [comment]
+1

**Comment by ExpandedMind** [comment]
me too, not able to debug my test methods in integration-test folders

**Comment by tkrullmann** [comment]
I don't remember what IntelliJ version the original issue referred to, but this seems to work fine now (tested again with 2.1.0 and IntelliJ Ultimate 2018.3)
