### ISSUE TITLE
Handling of 'resources' folder 

### ISSUE THREAD

**Issue by MartinAhrer** [unbroken-dome/gradle-testsets-plugin#18]
I have added an integrationTest source to an IDEA project with the 'idea' plugin applied (java and groovy too)

```
testSets {
    integrationTest
}
```

IDEA marks the `src/integrationTest/groovy` (and `resources`) as directories containing sources and resources in the source tree view. The filesystem layout is as follows

```
├── integrationTest
│   ├── groovy
│   │   └── at
│   │       └── martinahrer
│   │           └── service
│   │               └── integrationtest
│   │                   └── HomeIntegrationSpecification.groovy
│   └── resources
│       ├── application.properties
│       └── application.yml
└── main
    ├── java
    │   └── at
    │       └── martinahrer
    │           └── service
    │               └── ServiceApplication.java
    └── resources
        └── bootstrap.ml
```

When running the integration test from IDEA it looks like `src/integrationTest/resources` is not included in the execution class path. The file application.properties should be loaded (the application is based on Spring Boot) but is not and fails. Running the same setup from command line (`gradle integrationTest`) the test is going green.

Renaming the integrationTest to test (as supported by the Gradle groovy source set) the application works. The same applies when just moving application.properties into src/main/resources.

So the question is if there is any special setup required for the resources folder or is this an IDEA issue. I know that IDEA is not able to isolate various source sets from each other. But I guess this is not the root cause here?

**Comment by wujek-srujek** [comment]
I'm observing the same issue and it's driving me crazy. But, as you noticed yourself, when run on the command line with Gradle, all is fine and it works. I think this is an IDEA issue and you should open on issue in their tracker.  I will be happy to cast my vote in case you do, just add a link.

**Comment by wujek-srujek** [comment]
There actually is a ticket already, and a fix was bound to come with IDEA 15, but now it's rescheduled to 16..., more here: https://youtrack.jetbrains.com/issue/IDEA-138076

There exists a workaround which works for me, found here: https://youtrack.jetbrains.com/issue/IDEA-128966#comment=27-884771

As we are using the test-sets plugin, all we need is this:

```
sourceSets {
    if(System.properties.'idea.active') {
        main {
            resources.srcDir file('src/integrationTest/resources')
        }
    }
}
```

**Comment by tkrullmann** [comment]
It seems that starting with some 2016 version IDEA is not calling the Gradle "idea" plugin at all anymore, effectively stopping any Gradle plugin from modifying the IDEA project or module files.

However, IDEA support should work fine with the "separate module per source set" option.
