### ISSUE TITLE
Plugin does not get automatically applied to subprojects

### ISSUE THREAD

**Issue by Flowdalic** [unbroken-dome/gradle-testsets-plugin#2]
Minor nit: I had to

``` groovy
subprojects {
     apply plugin: 'org.unbroken-dome.test-sets'
}
```

in order to get the 'integrationTest' task for my subprojects also (it was already available for the root project).

**Comment by unbroken-dome** [comment]
Yes, this is the intended behavior. Only properties and methods are automatically inherited by subprojects, but not plugins or other domain objects like source sets etc.

The `subprojects { }` clause you used is the correct way to do that.
