### ISSUE TITLE
Version 1.3.0 not available

### ISSUE THREAD

**Issue by acisternino** [unbroken-dome/gradle-testsets-plugin#22]
Version 1.3.0 is not available neither from jcenter nor from plugins.gradle.org.

Maybe, if it has not been released yet, it would be better to add a few lines to the README.

**Comment by drjasonharrison** [comment]
The most recent version I see is 1.2.0.

**Comment by tkrullmann** [comment]
This has been fixed now. When plugins.gradle.org switched to their own repositories, my plugins weren't automatically recognized.
1.3.0 and 1.3.1 should now be properly published.
