### ISSUE TITLE
Expected output for gradle tasks

### ISSUE THREAD

**Issue by nesnes81** [unbroken-dome/gradle-testsets-plugin#23]
Can you help me understand why if I have something like this in my build.gradle:

```
testSets {
    integrationTest { dirName = 'integration-test' }
}
```

And I run

```
 > gradle tasks
```

I don't see "integrationTest" listed in the output?

Yet when I run

```
> gradle build
```

I see the task "integrationTest" does exist and is run?

**Comment by Dispader** [comment]
With the build

```Groovy
plugins {
    id 'org.unbroken-dome.test-sets' version '1.2.0'
}

testSets {
    integrationTest { dirName = 'integration-test' }
}
```

I'm seeing `integrationTest` in the `gradle tasks` output

```
(~/Development/tmp/testsets-subtasks) master {azazel}02:19am] gradle tasks
:tasks

------------------------------------------------------------
All tasks runnable from root project
------------------------------------------------------------
[...]
Other tasks
-----------
integrationTest
integrationTestJar

Rules
-----
Pattern: clean<TaskName>: Cleans the output files of a task.
Pattern: build<ConfigurationName>: Assembles the artifacts of a configuration.
Pattern: upload<ConfigurationName>: Assembles and uploads the artifacts belonging to a configuration.

To see all tasks and more detail, run gradle tasks --all
[...]
```

Curiouser and curiouser.  @nesnes81 May I ask which version of Gradle you're using?

**Comment by tkrullmann** [comment]
The integrationTest task (and also the integrationTestJar task) try to set their `group` and `description` attributes using a convention mapping - which never seems to have worked as intended.

As a result, these tasks end up in the "other" group where they are hidden from `gradle tasks` (but not `gradle tasks --all`)

As a fix, I'll set these attributes directly when creating the tasks, i.e. no convention mapping. It isn't really necessary as they are not using any properties of the test set that may change after its creation.
