### ISSUE TITLE
JDK 1.8 required

### ISSUE THREAD

**Issue by drjasonharrison** [unbroken-dome/gradle-testsets-plugin#25]
The Readme.md states:
`"You will need to run Gradle with a JDK 1.7 or higher to use the plugin."`

However, if you use JDK 1.7 with gradle-testsets-plugin 1.2.0 you will get the following error for the build.gradle line with `apply plugin: 'org.unbroken-dome.test-sets'`

> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file "xxxxxxx/build.gradle" line: 34
> 
> * What went wrong:
> A problem occurred evaluating root project "xxxxxxx".
> java.lang.UnsupportedClassVersionError: org/unbrokendome/gradle/plugins/testsets/TestSetsPlugin : Unsupported major.minor version 52.0
> 

Is the intention to support JDK 1.7, or JDK 1.8?

**Comment by tkrullmann** [comment]
Hi, this has been fixed in 1.3.0. Could you please try again with the latest version?

**Comment by drjasonharrison** [comment]
Sorry, I see 1.3.1 at jcenter, but 1.3.0 is not available. Same error.

**Comment by drjasonharrison** [comment]
Fixed in 1.3.2! Thank you very much!
