### ISSUE TITLE
When using Intellij's "separate module for each source set" resources aren't part of build

### ISSUE THREAD

**Issue by nickgieschen** [unbroken-dome/gradle-testsets-plugin#27]
When I check "separate module for each source set", I notice that in the generated build dir anything in the integrationTest/resources directory isn't getting copied to build and is thus not on the classpath. When I uncheck this settings, then everything is fine.

**Comment by tkrullmann** [comment]
Hi @nickgieschen, I tried reproducing this issue with the following simple project:

```groovy
plugins {
    id 'java'
    id 'org.unbroken-dome.test-sets' version '1.3.2'
}

testSets {
    integrationTest
}
```

I put a single file into `src/integrationTest/resources`; when I build the project from IntelliJ it is copied into `build/resources/integrationTest`:

![screenshot1](https://cloud.githubusercontent.com/assets/13819430/22758753/4ee80b50-ee50-11e6-8356-bc454cba7927.PNG)

(Unfortunately it's _also_ copied to `out/production/<projectName>`, but that seems to be a bug in IntelliJ...)

After doing the Gradle refresh, my project structure looks like this

![screenshot2](https://cloud.githubusercontent.com/assets/13819430/22758879/b9bba3c4-ee50-11e6-8f63-4480f76c0f2e.PNG)
