### ISSUE TITLE
Option to insert test fixture code before test

### ISSUE THREAD

**Issue by digulla** [unbroken-dome/gradle-testsets-plugin#29]
I often have the situation where I want to write a test fixture / support library to make writing tests easier for me and for people using the main code.

For this, the build order has to be `main` -> `testFixture` -> `test`.

Can you add an option to your plugin which allows to insert new test sets *before* the normal tests?

**Comment by tkrullmann** [comment]
Hi,
is `testFixture` only a support library for tests? It's not 100% what this plugin is intended for, but maybe the following could work:

1. Have the test set `testFixture` publish an artifact -> you will get a `testFixtureJar` task
2. Make the predefined test set `unitTest` extend from your test fixture
3. Create an artifact configuration that other projects can depend on
4. Create an artifact that contains the `testFixtureJar`

```groovy
testSets {
    testFixture { createArtifact = true }  /* 1 */
    unitTest.extendsFrom testFixture  /* 2 */
}

configurations {
    testFixture.extendsFrom testFixtureRuntime  /* 3 */
}

artifacts {
    testFixture testFixtureJar  /* 4 */
}
```

Other projects can now depend on the test library by specifying the `testFixture` configuration in the dependency:
```groovy
dependencies {
    testCompile project(path: ':project-path', configuration: 'testFixture')
}
```

Of course, doing this with a testSet will also create a `Test` task named `testFixture` which might name-clash with the configuration or the artifact.
Let me know if this approach works, then I'd be happy to add it to the documentation!

**Comment by tkrullmann** [comment]
I'm just seeing that item (2) is problematic, because every new test set implicitly extends from `unitTest`, so you'd get a cyclic dependency with that code.

**Comment by digulla** [comment]
Currently, my plugin looks like so:

```
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.tasks.bundling.Jar
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import org.gradle.plugins.ide.eclipse.model.EclipseModel

class JUnitSupportJarPlugin implements Plugin<Project> {

    Logger log = LoggerFactory.getLogger(JUnitSupportJarPlugin)

    void apply(Project project) {
        log.debug('Applying JUnit plugin to {}', project)
        
        project.sourceSets {
            junit {
                compileClasspath += main.output
                runtimeClasspath += main.output
            }
            
            test {
                compileClasspath += junit.output
                runtimeClasspath += junit.output
            }
        }
        
        project.configurations {
            junit {
                description = 'JUnit Support JAR classpath'
            }
            
            junitCompile.extendsFrom(compile)
            junitCompileOnly.extendsFrom(compileOnly)
            junitRuntime.extendsFrom(runtime)
            testCompile.extendsFrom(junitCompileOnly) // This has to be junitCompileOnly; otherwise the tests won't see optional dependencies of the JUnit support code. 
            testCompileOnly.extendsFrom(junitCompileOnly)
            testRuntime.extendsFrom(junitRuntime)
        }
        
        registerArtifacts(project)
    }
    
    def registerArtifacts(Project project) {
        def junitClasses = ":${project.name}:junitClasses"
        project.task('junitJar', type: Jar, dependsOn: junitClasses) {
            from project.sourceSets.junit.output
            archiveName "${baseName}-${version}-junit.jar"
        }
        
        project.task('junitSourceJar', type: Jar, dependsOn: junitClasses) {
            from project.sourceSets.junit.allSource
            archiveName "${baseName}-${version}-junit-sources.jar"
        }
        
        project.artifacts {
            archives project.junitJar
            archives project.junitSourceJar
        }
    }
}
```

The classpath magic is mostly in `project.sourceSets{}` where I squeeze the new `junit` code between `main` and `test` so each one can see all the code of the previous step.

The code in `project.configurations{}` does the same for the classpaths.

So no intermediate artifact necessary.

**Comment by tkrullmann** [comment]
Ok, so where does the testsets plugin come in here? Is this a use case for which you would like the testsets plugin instead, or combine it with your plugin?

Also, some advice on the plugin above:
1. You shouldn't modify the classpath of a source set directly, it's clearer to use configurations and dependencies instead.
So instead of
```
sourceSets {
    junit {
        compileClasspath += main.output
        runtimeClasspath += main.output
    }
}
```
You should just write
```
sourceSets { junit }
dependencies {
    junitCompile sourceSets.main.output
}
```

Because of the implicit `junitRuntime.extendsFrom junitCompile` you don't have to add the dependency to both.

2. The `archives` configuration is the default configuration for other projects to depend on.
If you add artifacts to the `archives` configuration that are only needed for testing, they will still end up on the main compile (or runtime) classpath for any dependent project. So it's probably better to use a separate configuration for these artifacts:
```
configurations { junitArchives }
artifacts {
    junitArchives project.junitJar
}
```

And then you can distinguish between "production" and test dependencies in other projects:
```
dependencies {
    compile project(':otherProject')
    testCompile project(path: ':otherProject', configuration: 'junitArchives')
}
```

**Comment by digulla** [comment]
I would like to merge my code into your plugin, if that makes sense. Right now, I can solve my problem and you can solve yours, so there is no pressure.

As for using the dependencies: That's what I had before but it was brittle. The guys of Buildship suggested to do it this way (see https://github.com/eclipse/buildship/issues/429).

With your approach, either Gradle or Eclipse will fail to compile the code because either classes or JARs won't be on some classpaths. I don't understand this completely, unfortunately. It also doesn't help that I have optional dependencies which aren't really supported by Gradle.

Re archives: I see what you mean. In my case, that didn't make a big difference because all my other projects use Maven, that's why I never noticed. Another reason to merge my code with yours :-)

**Comment by tkrullmann** [comment]
Closing this issue as this feature is now implemented as "test libraries" in 2.0

**Comment by digulla** [comment]
I can't find anything useful when I google for "gradle test libraries". Do you have a link which explains how to set this up?

**Comment by tkrullmann** [comment]
It's a new feature of this plugin, not a Gradle feature :-)
It should be documented in the [README](https://github.com/unbroken-dome/gradle-testsets-plugin#test-libraries), let me know if it works for you!

**Comment by digulla** [comment]
Where would I put the code that should go into `${project}-${version}-testCommon.jar`? i.e. what is the path? Is it `src/testCommon/java/`?

**Comment by digulla** [comment]
Ping?

**Comment by tkrullmann** [comment]
Sorry for the late answer...
If you have a test library called `testCommon` then by default it'll only be a source set inside the project. You can publish it as an artifact by setting `createArtifact` to `true`:

```
testSets {
    libraries {
        testCommon {
            createArtifact = true
            classifier = 'tests'   // The classifier defaults to the name of the test set / test library
        }
    }
}
```

And yes, then you would put the sources into `src/testCommon/java` (which you can change by setting the `dirName` property)

**Comment by digulla** [comment]
To clarify the documentation (https://github.com/unbroken-dome/gradle-testsets-plugin#test-libraries) please add this at the end:

The same applied to unitTest (just replace `integrationTest` with `unitTest` in the text above).

Sources for this shared test code library would go into `src/testCommon/java` (which you can change by setting the `dirName` property)
