### ISSUE TITLE
java-library compat / gradle 4

### ISSUE THREAD

**Issue by tobad357** [unbroken-dome/gradle-testsets-plugin#34]
In gradle 4 there is a java-library plugin which creates two configurations "api","implementation"
These then get put into the configurations compileClasspath/testCompileClasspath and runtimeClasspath/testRuntimeClasspath respectively
But they don't get added to runtime/testRuntime compile/compileRuntime as these seem to be deprecated. This in turn means the testset config don't get the libs added to the classpath.

I think the bug is that testsets extends testRuntime and testCompile instead of testRuntimeClasspath and testCompileClasspath

**Comment by tkrullmann** [comment]
Hi, and thanks for the contribution!
I've been meaning to look at the new configurations from the java-library plugin, and ensure the compatibility.

But I'm afraid it isn't going to be this easy. Apart from backward compatibility with pre-3.4 Gradle versions, there are plugins for other languages (esp. Groovy and Kotlin) that are reportedly not working well with the new configurations, so you have no choice but falling back to `compile` and `runtime`. Given that many people will write their tests in Groovy, this has to be considered carefully.

In my opinion the Gradle team tends to be a bit rash with deprecation, often deprecating things that don't have a stable replacement yet. So I wouldn't put too much stock in `compile` and `runtime` being deprecated.

**Comment by tobad357** [comment]
For future reference
Kotlin issues
https://youtrack.jetbrains.com/issue/KT-18497
https://youtrack.jetbrains.com/issue/KT-18544

Compatibility issues mentioned in Gradle docs
https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_known_issues_compat

**Comment by alexkleiman** [comment]
I was able to work around this by adding the following to my Gradle build:

```
configurations {
    integrationTestImplementation {
        extendsFrom testImplementation
    }

    integrationTestCompileOnly {
        extendsFrom testCompileOnly
    }

    integrationTestRuntimeOnly {
        extendsFrom testRuntimeOnly
    }

    integrationTestCompileClasspath {
        extendsFrom testCompileClasspath
    }

    integrationTestRuntimeClasspath {
        extendsFrom testRuntimeClasspath
    }
}
```

This seems to do the trick for Java, at least.

**Comment by tkrullmann** [comment]
The plugin now honors the `implementation` and `runtimeOnly` configurations when extending test sets, in addition to the `compile` and `runtime` configurations as before.

This is analogous to the configuration extensions that the `java` plugin creates for the "test" test set.

@alexkleiman 
The `compileOnly` configurations should not be inherited, they are intended for optional and compile-time-only dependencies (like annotation processors). These dependencies are typically closely related to the source code of the respective source set. (The standard java plugin doesn't add and extension from `testCompileOnly` to `compileOnly` either).

Also, `compileClasspath` and `runtimeClasspath` are "derived" configurations, so adding these extensions should be unnecessary.

**Comment by alexkleiman** [comment]
@tkrullmann got it, thank you for the details!
