### ISSUE TITLE
Custom resolution strategies are not working for integrationTest task

### ISSUE THREAD

**Issue by marksarnold** [unbroken-dome/gradle-testsets-plugin#36]
It seems like version resolution strategies are ignored by the plugin's integrationTest task.
Example:

```
configurations {
  provided
  all*.resolutionStrategy {
    force 'org.jboss.logging:jboss-logging:3.2.0.Final'
  }
}
```

Works for compile, test, and ear tasks, but for integrationTest, it does not work (meaning gradle pulls some other version than the one I specified)
This is both with the STS eclipse plugin and also when calling gradle from the command line.
Gradle is version 3.5

**Comment by tkrullmann** [comment]
Hi @marksarnold, I haven't been able to reproduce this. Could you paste a bit more of your build script (most importantly, the `dependencies` and the `testSets` blocks)?

My suspicion is that your `testSets` block appears _after_ your `configurations` block, so the `configurations.all` property won't know about the `integrationTest` related configurations at that time.

In that case, either move the `testSets` block further up, or use the `configurations.all { }` method instead. which also applies to any future configurations:

```groovy
configurations {
    all {
        resolutionStrategy {
            force 'org.jboss.logging:jboss-logging:3.2.0.Final'
        }
    }
}
```

**Comment by marksarnold** [comment]
> My suspicion is that your testSets block appears after your configurations block,

That is the case. Will try changing that and see if it fixes the problem...

**Comment by marksarnold** [comment]
So before, it was like this:
```
configurations {
...
}

repositories {
...
}

buildscript {
  repositories {
    ...
  }
  dependencies {
    ...
    classpath 'org.unbroken-dome.gradle-plugins:gradle-testsets-plugin:1.0.2' // Java 7 version
  }
}

testSets {
    integrationTest
}

dependencies {
...
}
```

I pulled testSets up and now it is:

```
testSets {
    integrationTest
}

configurations {
...
}

repositories {
...
}

buildscript {
  repositories {
    ...
  }
  dependencies {
    ...
    classpath 'org.unbroken-dome.gradle-plugins:gradle-testsets-plugin:1.0.2' // Java 7 version
  }
}

dependencies {
...
}

```
This fixed the problem.
Is there anything I might break by pulling testSets all the way up? Have ran a quick build and not found anything wrong so far...
Thank you, 
Mark

**Comment by tkrullmann** [comment]
Great that it works now. No issue I can think of, apart from the pitfall that you just experienced.
I'd strongly recommend using
```
configurations.all {
    resolutionStrategy { ... }
}
```
over
```
configurations.all*.resolutionStrategy { ... }
```
because the closure version will also be called on any configurations that are added afterwards.
