### ISSUE TITLE
Dependencies do not refreshed. 

### ISSUE THREAD

**Issue by joyfulj** [unbroken-dome/gradle-testsets-plugin#37]
Hi, I like your gradle-testsets-plugin.
This is very useful for my work.

But there is a trouble. I wish it could be solved.
 
If I add dependencies in dependencies, They are not refreshed.
For example, I add my SNAPSHOT library in dependencies.
```gradle
integrationTestCompile group: 'com.mygroup', name: 'my-library', version: '1.0.0-SNAPSHOT'
```

After I deploy new SNAPSHOT library in my local nexus repository,
New SNAPSHOT library is not downloaded from nexus.

'gradle --refresh-dependencies' options did not work.
```gradle
configurations.all {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}
```
'cacheChangingModulesFor' configuration did not work.

'changing=true' option also did not work.

**To solve this problem,**
I have to remove my gradle cache metadata descriptors.
```
/Users/myuser/.gradle/caches/modules-2/metadata-2.23/descriptors
```

or
I should put my library into testCompile
```gradle
testCompile group: 'com.mygroup', name: 'my-library', version: '1.0.0-SNAPSHOT'
```

Thanks.

**Comment by tkrullmann** [comment]
Hi,
the test sets plugin doesn't deal with dependencies at all, just configurations - so I think that the issue might not directly be related to the plugin.

As far as I know Gradle doesn't assign any special meaning to SNAPSHOT dependencies - that's purely a Maven concept. So for `resolutionStrategy.cacheChangingModulesFor` to have any effect, you probably need to mark your dependency as changing manually:

```groovy
integrationTestCompile group: 'com.mygroup', name: 'my-library', version: '1.0.0-SNAPSHOT', changing: true
```
see https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ExternalModuleDependency.html#setChanging(boolean)

**Comment by tkrullmann** [comment]
Did this work for you?
