### ISSUE TITLE
Create separated reports

### ISSUE THREAD

**Issue by geowarin** [unbroken-dome/gradle-testsets-plugin#4]
Hello,
First, thank you for your plugin, it's a very good idea.

It would be nice if each test task could generate a separated report at the end.
Right now, the reports are all generated in the default dir, `build/reports/tests`.
If you run multiple test tasks, they will overwrite each other's reports.

It can be fixed with very little config but it would be nice if the plugin could take care of that:

``` groovy
tasks.withType(Test) {
    reports.html.destination = file("${reporting.baseDir}/${name}")
}
```

What do you think?

**Comment by unbroken-dome** [comment]
Hi,
I think it's a great idea! Haven't thought much about the reporting part yet, but it's definitely something worth separating.

**Comment by geowarin** [comment]
Awesome! thanks
