### ISSUE TITLE
Classpath is set incorrectly when using `tasks.withType(Test)` configuration

### ISSUE THREAD

**Issue by ketan** [unbroken-dome/gradle-testsets-plugin#40]
I'm applying a `classpath` to all tests in a multi-project build using `tasks.withType`. This causes the `testClassesDirs` to not be on the classpath of the test task configured by the plugin. Here is a test case to reproduce. Save the file as `build.gradle` and run with `gradle clean -q -PadditionalClasspath` and then with `./gradlew clean -q`. You'll see the following outputs:

As you'll see `integrationTest` dir is nowhere on the classpath in one of the cases. I'll and work on a fix in the plugin, but in the meanwhile, if there's a workaround — I'd appreciate any pointers :)

```
$./gradlew clean -q
[/private/tmp/foo/build/classes/java/integrationTest, /private/tmp/foo/build/resources/integrationTest, /private/tmp/foo/build/classes/java/main, /private/tmp/foo/build/resources/main]
$./gradlew clean -q -PadditionalClasspath
[/private/tmp/foo/build/classes/java/test, /private/tmp/foo/build/resources/test, /private/tmp/foo/build/classes/java/main, /private/tmp/foo/build/resources/main, /private/tmp/foo/foo]
```

```groovy
plugins {
    id 'org.unbroken-dome.test-sets' version '1.4.2'
}

apply plugin: 'java'

tasks.withType(Test) {
  if (project.hasProperty('additionalClasspath')) {
    classpath += files('foo')
  }
}

testSets {
    integrationTest
}

println integrationTest.classpath.files
```

**Comment by tkrullmann** [comment]
Hi,

I'm afraid this is not a bug - the plugin uses Gradle's convention mapping mechanism to configure the test task. The conventional / default values are not applied once you configure them directly, like `classpath` in your example.

What you could try is to wrap your additional classpath configuration inside a `project.afterEvaluate { }` block. That way it should be applied only after the convention mappings.
