### ISSUE TITLE
How to use a build artifact as a test resource

### ISSUE THREAD

**Issue by amimas** [unbroken-dome/gradle-testsets-plugin#41]
Hi,

This might be a generic gradle question. How can I use a build artifact as one of the test resources?

I'm needed add "integration test" to my project and also wanted to keep them separate from unit test. This plugin seems to be just the tool for that purpose. So far it's working great. I have a separate sourceset called `integrationTest` and I have following directories in my project

```
src/integrationTest/groovy/
src/integrationTest/resource/
```
Now I need to enhance the existing integration test cases to use one of the artifacts produced after building the project (`gradlew build`).  The artifacts are stored in `build` directory as per gradle convention.

Is there any way I can configure my gradle build script so that `integrationTest` sourcesets recognizes build artifacts?

**Comment by tkrullmann** [comment]
Hi,
yes that's quite a general Gradle question :-)
I suppose you would like to have your main JAR file as a classpath resource for the integration test.

Most straightforward way is to copy the JAR to the integrationTest resources output folder, and probably rename it because you want to have a fixed filename when referring to it.

```groovy
task copyMainJarToIntegrationTestResources(type: Copy) {
    from jar
    into sourceSets.integrationTest.resources.outputDir
    rename { "${jar.baseName}.jar" }
}
```

Then your `integrationTest` task should depend on this copy operation:
```groovy
integrationTest.dependsOn copyMainJarToIntegrationTestResources
```

Hope that helps.

**Comment by amimas** [comment]
Thanks. I managed to solve it slightly differently but the idea is same.

Gradle already has a task tied to each sourcesets called `process<sourceset-name>Resources`. So, in my example in this thread, Gradle adds a task named `processIntegrationTestResources`. This task automatically copies files from `src/integrationTest/resources` to `build/resources/integrationTest`.

So, I added my build artifact that needs to be included in the resource (`build/resources/integrationTest`) like this:

```gradle
processIntegrationTestResources {
    from (zipTree (file("$buildDir/distributions/${project.name}-${version}.zip"))) {
        //Unzips this build artifact into the resource's subdirectory named 'myArchive' relative to resource directory
        into "myArchive"
    }
}
```

Ideally I'd like to change the `from...` line to be something like this so that I don't have to specify the artifact location, but haven't been able to get that to work yet.

```
from (myArchiveTask.outputs)
```

**Comment by tkrullmann** [comment]
Nice! It looks like you're using the `distribution` plugin and its `distZip` task.
`distZip` is also an archive task, so you can also refer to the archive that's being built from the `archivePath` property:

```groovy
processIntegrationTestResources {
    from zipTree(distZip.archivePath) {
        into 'myArchive'
    }
}
```

That way you don't have to repeat the logic of how the zip file name is assembled.

You should probably also add a `dependsOn distZip` to make sure the tasks are run in the correct order.
