### ISSUE TITLE
How to set common configuration for multiple sourcesets

### ISSUE THREAD

**Issue by amimas** [unbroken-dome/gradle-testsets-plugin#44]
Hello,

I've used this plugin to create 2 sourcesets named `integrationTest` and `functionalTest`. The 2nd sourceset is extended from the 1st one.

There are some common configurations for both of them. For example:
```gradle
integrationTest {
  outputs.upToDateWhen { false }
  testLogging { ... }
}
```
How can I get `functionalTest` to inherit those same configurations?

Do I need to use task graph to handle this or does this plugin already provide a feature for this that I'm not using?

**Comment by tkrullmann** [comment]
Hi,
I'm afraid the "inheritance" you're trying to achieve isn't possible. There is no direct relationship between the `Test` tasks created for each test set. Having task configuration automatically inherited would also go a bit against the general approach of Gradle, where everything should be simple but explicit and obvious.

So, something you could try instead: Configure multiple extra `Test` tasks at once, e.g.
```groovy
[integrationTest, functionalTest]*.configure {
    outputs.upToDateWhen { false }
    // ...
}
```

Or, if you want to go through the `testSets`, you can get to the `Test` task via the `testTaskName` property:
```groovy
testSets.matching { it.name != 'unitTest' }.all {
    tasks[it.testTaskName].configure {
        outputs.upToDateWhen { false }
        // ...
    }
}
```
