### ISSUE TITLE
Version 1.5.1 not found in jcenter()

### ISSUE THREAD

**Issue by stefanscheidt** [unbroken-dome/gradle-testsets-plugin#49]
Could not find org.unbroken-dome.gradle-plugins:gradle-testsets-plugin:1.5.1.
Searched in the following locations:
    https://jcenter.bintray.com/org/unbroken-dome/gradle-plugins/gradle-testsets-plugin/1.5.1/gradle-testsets-plugin-1.5.1.pom
    https://jcenter.bintray.com/org/unbroken-dome/gradle-plugins/gradle-testsets-plugin/1.5.1/gradle-testsets-plugin-1.5.1.jar

**Comment by tkrullmann** [comment]
Fixed. Thank you!
