### ISSUE TITLE
TestSets do not seem to modify Eclipse .classpath for ${testSet}Compile dependencies

### ISSUE THREAD

**Issue by Dispader** [unbroken-dome/gradle-testsets-plugin#5]
Hey there,

Firstly, thank you for the wonderful plugin!  It's looking really promising for some projects here, and is much appreciated.  Many thanks!

I may be misunderstanding the plugin, but I believe I may have found a bug?  In [this Gist example](https://gist.github.com/Dispader/0be7caa483fa9faf4320), it seems that a `gradle eclipse` isn't producing `.classpath` entries for the `integrationTest` testSet.

I might well be misunderstanding things, but any help would be much appreciated.

Thanks again!

Jake

**Comment by unbroken-dome** [comment]
Hi Dispader, and sorry for the late response!
I remember the Gradle-Eclipse integration to be shaky at best, with repeated rounds of "Refresh All" and command line builds until everything worked. I will look into it!

**Comment by unbroken-dome** [comment]
This seems to have been (inadvertently) fixed with 1.1.0.
Running "gradle eclipse" on your build file does produce a faulty .classpath in 1.0.2, but it does what it should in 1.1.0.

**Comment by Dispader** [comment]
Thank you, sir.  I'll give it a go!  And thanks again for the great project.
