### ISSUE TITLE
Creating test set name dynamically

### ISSUE THREAD

**Issue by rahulaga** [unbroken-dome/gradle-testsets-plugin#51]
This is a question on how I can name the testSet dynamically - and maybe more of a groovy question. I am new to groovy and gradle so any help is much appreciated.

What I am trying to is create multiple test sets (in a loop). I have a set of `names` so I am trying to do as follows in my own plugin:

```
names.each { name ->
            def testSetName = "testName"+name
            project.configure(project) {
                apply plugin: 'org.unbroken-dome.test-sets'
                testSets {
                    testSetName {
                        ...
                    }
                }
...
```
The `testSetName` is what I want dynamically added to my project. The above does not work and it fails saying a String cannot be applied to a method expecting a closure. What would be the way to do this?

Thanks

**Comment by tkrullmann** [comment]
Hi,

The `testSets` container is just another `NamedDomainObjectSet`, you'll find a lot of them in Gradle, for example `tasks` and `configurations`. There's several ways how you can achieve what you want. Pick the one that you like most :-)

First, you can use the container's `create` method directly (actually the "dynamic" method is just Gradle's syntactic sugar for calling `create`):

```groovy
testSets.create(testSetName) {
    // ...
}
```

You can also enclose the variable name in a GString, which will trigger the behavior of invoking a dynamic method:

```groovy
testSets {
    "$testSetName" {
        // ...
    }
}
```

By the way, I think that `project.configure(project)` in your example is redundant; configuring the `project` object is exactly what you are doing already in your build script.

Hope this helps!

**Comment by rahulaga** [comment]
Thank you @tkrullmann, exactly what I needed.
