### ISSUE TITLE
Don't remove IDEA module configuration

### ISSUE THREAD

**Issue by pkoenig10** [unbroken-dome/gradle-testsets-plugin#56]
This feature was removed in 2.0. While IDEA’s Gradle import may bypass the `IdeaModel`, creating the IDEA project using the [IDEA plugin ](https://docs.gradle.org/current/userguide/idea_plugin.html) does not. When using the IDEA plugin to generate the project, this functionality is still valuable.

**Comment by tkrullmann** [comment]
it should be working again in 2.0.2 :-)
