### ISSUE TITLE
Unit tests run during other test-set phases when using Spek

### ISSUE THREAD

**Issue by jcornaz** [unbroken-dome/gradle-testsets-plugin#62]
Hi, 

When wirting tests with  [Spek](https://spekframework.org), given the following configuration:
```kotlin
testSets {
  val integrationTest by creating
}

tasks.withType(Test::class).all {
  useJUnitPlatform {
    includeEngines("spek2")
  }
}
```

Running `gradlew integrationTest` executes the specifications present in *both* `test` and `integrationTest` directories. And running `gradlew test integrationTest` run twice specifications present in the `test` directory.

Any idea on how I could solve this issue?

**Comment by tkrullmann** [comment]
I tried your setup with Spek and it seems to me that Spek, unlike JUnit, scans the entire classpath for tests, which is probably a bug.

Gradle's `Test` tasks have two separate properties for this, `classpath` (which contains the entire classpath) and `testClassesDirs` (which should be the only place to scan for tests). The Spek runner doesn't seem to respect this.

You can verify this by logging the files in the two properties before the test is executed:
```kotlin
tasks.withType<Test> {
    doFirst {
        println ("""
            Test task "$name":
              testClassesDirs: ${testClassesDirs.joinToString()}
              classpath: ${classpath.joinToString()}
        """.trimIndent())
    }
}
```

**Comment by jcornaz** [comment]
Thanks @tkrullmann. It looks like a bug on the spek side indeed.

I'll seek a resolution in Spek: spekframework/spek/issues/572.

**Comment by jcornaz** [comment]
@tkrullmann, Actually, why are the unit tests in the classpath of my integration tests?

Reading:
* https://github.com/unbroken-dome/gradle-testsets-plugin#extending-other-test-sets
* https://github.com/unbroken-dome/gradle-testsets-plugin#predefined-unit-test-set

I understand that: 
>All new test sets implicitly extend the "unitTest" set.

and that
> It does not mean, however, that the source (classes / resources) of the extended test set will be available to the extending test set.

So, given my configuration, I expect my integration tests to have the same dependencies than my unit tests, but I do not expect to find my unit tests in the classpath of my integration tests.

**Comment by jcornaz** [comment]
Apparently the latest release solved this problem. Thank you very much.
