### ISSUE TITLE
gradle output being added to eclipse classpath

### ISSUE THREAD

**Issue by jpschewe** [unbroken-dome/gradle-testsets-plugin#77]
I'm using the testsets plugin version 2.1.1 with gradle 5.3. 

When I execute the "eclipseClasspath" task I am finding that the test output directory from gradle is included in the eclipse classpath. I have setup eclipse and gradle with separate output directories so that they don't collide. This addition to the eclipse classpath file is causing problems for eclipse as these directories don't exist until a gradle build has completed. Is there a way to ensure that testsets doesn't add these entries to the eclipse classpath?

The entries are
```xml
        <classpathentry kind="lib" path="/data/home/jpschewe/projects/fll-sw/working-dir/build/classes/java/test">
                <attributes>
                        <attribute name="gradle_used_by_scope" value="integrationTest,test"/>
                </attributes>
        </classpathentry>
        <classpathentry kind="lib" path="/data/home/jpschewe/projects/fll-sw/working-dir/build/resources/test">
                <attributes>
                        <attribute name="gradle_used_by_scope" value="integrationTest,test"/>
                </attributes>
        </classpathentry>
```

I have configured testsets with
```groovy
testSets {
    integrationTest
}
```

**Comment by tkrullmann** [comment]
Hi! Thanks for the report.
I don't use Eclipse a lot myself, back when I first created this plugin it had basically no support with having multiple source sets in the same project, that's why I added this behavior.
If this has improved now on Eclipse's side, we could certainly make this feature optional.

**Comment by jpschewe** [comment]
Eclipse appears to have support for multiple source sets now. However the testsets plugin causes these extra classpath entries. If you look at the referenced commit you'll see what I needed to add to the eclipse plugin to remove these extra classpath entries. If you have any ideas why testsets is adding these and how to make it stop adding these, that would be great. In the mean time I've worked around this by having gradle modify the classpath that is generated.

**Comment by tkrullmann** [comment]
Tried this again with a recent version of Eclipse (Spring Tool Suite 4.6.0.RELEASE), it seems that "refresh Gradle project" completely ignores the build script's / plugin's modifications to the `EclipseModel`.

As for marking a source set as test code, it seems that Eclipse will base this entirely on the fact that the source set name contains the substring "test".

**Comment by tkrullmann** [comment]
I will disable this feature by default - as it seems quite useless now -, but will add a project property to enable it on demand.

**Comment by jpschewe** [comment]
Unfortunately this is still broken. Using "lib" instead of "src" is the problem at this point. I need to enable `org.unbroken-dome.test-sets.modifyEclipseClasspath=true` otherwise the libraries that I mark as `integrationTestImplementation` aren't known to eclipse.
