### ISSUE TITLE
Custom test set dependencies not available in IDEA TEST scope

### ISSUE THREAD

**Issue by wujek-srujek** [unbroken-dome/gradle-testsets-plugin#9]
I'm defining an 'integrationTest' test set and according to the documentation, this should add all the dependencies to the TEST scope in IDEA. However, this doesn't happen, and I can only make it work using the following:

```
idea {
    module {
        scopes.TEST.plus += [configurations.integrationTestRuntime]
    }
}
```

I have a multimodule project.

**Comment by wujek-srujek** [comment]
I was using 1.0.2, and the documentation was written for 1.1.0, I guess, so I think this ticket can be closed. After the upgrade to 1.2.0 it seems to be working fine.

**Comment by tkrullmann** [comment]
Great, glad it's working now :-)
